version: '3.7'

services:
  geth-bootnode:
    hostname: geth-bootnode
    image: geth-client-poa
    build:
      context: .
      args:
        - ACCOUNT_PASSWORD=password123
    command:
      --nodekeyhex="b0ac22adcad37213c7c565810a50f1772291e7b0ce53fb73e7ec2a3c75bc13b5"
      --nodiscover
      --ipcdisable
      --networkid=12345
      --netrestrict="172.16.254.0/28"
    networks:
      priv-eth-net:

  geth-node1:
    hostname: geth-node1
    image: geth-client-poa
    depends_on:
      - geth-bootnode
    command:
      --bootnodes="enode://af22c29c316ad069cf48a09a4ad5cf04a251b411e45098888d114c6dd7f489a13786620d5953738762afa13711d4ffb3b19aa5de772d8af72f851f7e9c5b164a@geth-bootnode:30303"  
      --mine
      --networkid=12345
      --miner.etherbase=218C37A0305E14a7cE5fE661FA4537104B9E003e
      --unlock 218C37A0305E14a7cE5fE661FA4537104B9E003e 
      --password /root/password.txt
    networks:
      priv-eth-net:


      

  geth-node2:
    hostname: geth-node2
    image: geth-client-poa
    depends_on:
      - geth-bootnode
      - geth-node1
    command:
      --bootnodes="enode://af22c29c316ad069cf48a09a4ad5cf04a251b411e45098888d114c6dd7f489a13786620d5953738762afa13711d4ffb3b19aa5de772d8af72f851f7e9c5b164a@geth-bootnode:30303"
      --networkid=12345
      --unlock 7c22EAc04A9D3A715B47c48485299B6AD785b094 
      --password /root/password.txt
    networks:
      priv-eth-net:
  
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest 
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw 
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      priv-eth-net:

  prometheus:
    image: prom/prometheus:v2.25.0
    restart: always
    volumes:
      - ./prometheus_conf/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus_conf/rules:/etc/prometheus/rules
    ports:
      - "9090:9090"
    networks:
      priv-eth-net:
    depends_on:
      - cadvisor

  grafana:
    image: grafana/grafana:8.2.5
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./grafana_data:/var/lib/grafana
    networks:
      priv-eth-net:
    depends_on:
      - prometheus

networks:
  priv-eth-net:
    driver: bridge
    ipam:
      config:
      - subnet: 172.16.254.0/28

