version: '3.7'
volumes:
  influxdb_data: {}

services:
  geth-bootnode:
    hostname: geth-bootnode
    image: geth-client-poa
    build:
      context: .
      args:
        - ACCOUNT_PASSWORD=password123
    command:
      --nodekeyhex="b0ac22adcad37213c7c565810a50f1772291e7b0ce53fb73e7ec2a3c75bc13b5"
      --nodiscover
      --ipcdisable
      --networkid=12345
      --netrestrict="172.16.254.0/28"
      --metrics 
      --metrics.influxdb 
      --metrics.influxdb.endpoint "http://influxdb:8086" 
      --metrics.influxdb.username "geth" 
      --metrics.influxdb.password "geth"
    networks:
      priv-eth-net:

  geth-node1:
    hostname: geth-node1
    image: geth-client-poa
    depends_on:
      - geth-bootnode
    command:
      --bootnodes="enode://af22c29c316ad069cf48a09a4ad5cf04a251b411e45098888d114c6dd7f489a13786620d5953738762afa13711d4ffb3b19aa5de772d8af72f851f7e9c5b164a@geth-bootnode:30303"  
      --mine
      --networkid=12345
      --miner.etherbase=545A814C3cbF5bFfee81DeCaf4C2348B7810E541
      --unlock 545A814C3cbF5bFfee81DeCaf4C2348B7810E541 
      --password /root/password.txt
      --metrics 
      --metrics.influxdb 
      --metrics.influxdb.endpoint "http://influxdb:8086" 
      --metrics.influxdb.username "geth" 
      --metrics.influxdb.password "geth"
    networks:
      priv-eth-net:


  geth-node2:
    hostname: geth-node2
    image: geth-client-poa
    depends_on:
      - geth-bootnode
      - geth-node1
    command:
      --bootnodes="enode://af22c29c316ad069cf48a09a4ad5cf04a251b411e45098888d114c6dd7f489a13786620d5953738762afa13711d4ffb3b19aa5de772d8af72f851f7e9c5b164a@geth-bootnode:30303"
      --networkid=12345
      --unlock 33b199A469f2f75767D424C99F28E2C0b744a68A  
      --password /root/password.txt
      --metrics 
      --metrics.influxdb 
      --metrics.influxdb.endpoint "http://influxdb:8086" 
      --metrics.influxdb.username "geth" 
      --metrics.influxdb.password "geth"
    networks:
      priv-eth-net:
  

  influxdb:
    container_name: influxdb
    image: influxdb:1.8
    ports:
      - 8086:8086
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8086/ping"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
    restart: always
    env_file:
      - ./influxdb/influxdb.env
    volumes:
      - influxdb_data:/var/lib/influxdb2
      - ./influxdb/config.yml:/etc/influxdb2/config.yml
    networks:
      priv-eth-net:
    

  grafana:
    image: grafana/grafana:8.2.5
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./grafana_data:/var/lib/grafana
    networks:
      priv-eth-net:
    depends_on:
      - influxdb 

networks:
  priv-eth-net:
    driver: bridge
    ipam:
      config:
      - subnet: 172.16.254.0/28

